### PR TITLE
Docs: Add badge for number of lines of code

### PR DESCRIPTION
**Pull request by dkrako**
looks like this: [lines of code](https://github.com/aeye-lab/pymovements)

provided by: https://github.com/XAMPPRocky/tokei_rs

Also provided:

 [total lines](https://github.com/aeye-lab/pymovements)

 [blank lines](https://github.com/aeye-lab/pymovements)

 [files](https://github.com/aeye-lab/pymovements)

 [comments](https://github.com/aeye-lab/pymovements)

### CODE REVIEW

**Comment by SiQube** [comment]
why do you think we should add this?

**Comment by SiQube** [comment]
@theDebbister your opinion?

**Comment by dkrako** [comment]
I did it just for the lolz

**Comment by SiQube** [comment]
then I'd be against it :D

**Comment by theDebbister** [comment]
I don't have a strong opinion on this, but I think I would not add it, there are already quite a few badges

**Comment by dkrako** [comment]
haha alright

**Pull request closed without merging**
