### PR TITLE
feat: autodetect column names

### PR DESCRIPTION
**Pull request by prassepaul**
## Description

Added auto_column_detection

### CODE REVIEW

**Review by dkrako — CHANGES_REQUESTED** [review]
Great! Now all of this can be removed from `dataset_files.py` right?

https://github.com/aeye-lab/pymovements/blob/8edc901b229174a6dc40a2c1c454457d3bd7ef76/src/pymovements/dataset/dataset_files.py#L283-L313

**Review by dkrako — DISMISSED** [review]
Ah and now I noticed that the `auto_column_detect` argument should also be available for all the functions in `gaze.integration` and `gaze.io`. Could you add it to these functions too, please?

**Comment by prassepaul** [comment]
I did the changes

**Comment by dkrako** [comment]
this should be the fix: #729
can you approve and merge the changes afterwards from the mainbranch into your PR?

**Review by SiQube — APPROVED** [review]

**Pull request merged**
