### PR TITLE
ci: remove mypy ignore imports for matplotlib

### PR DESCRIPTION
**Pull request by SiQube**
needs #563 or #561

### CODE REVIEW

**Review by prassepaul — APPROVED** [review]

**Review by dkrako — APPROVED** [review]
Thank you for checking!

**Review by dkrako — CHANGES_REQUESTED** [review]
mypy raises the errors, as matplotlib is not the recent version there somehow:

```
matplotlib==3.7.3
```
(in line 13 in the error log)

- [ ] I think this PR should come with a requirement of matplotlib>=3.8.0

**Comment by SiQube** [comment]
okay how about we just kill mypy within github actions -- we're checking it via pre-commit.ci anyways. matplotlib 3.8 has dropped python 3.8... otherwise I'd say we stay at 3.7.3 with the already merged fix

**Comment by dkrako** [comment]
> okay how about we just kill mypy within github actions -- we're checking it via pre-commit.ci anyways. matplotlib 3.8 has dropped python 3.8... otherwise I'd say we stay at 3.7.3 with the already merged fix

The current numpy release is also python >=3.9: https://numpy.org/neps/nep-0029-deprecation_policy.html

I'm actually not that hesitant about dropping python 3.8 altogether (but then in a separate PR).

**Comment by SiQube** [comment]
requires #572

**Comment by ritchie46** [comment]
> fails due to polars not building wheels for windows, see [here](https://github.com/pola-rs/polars/issues/11355), and [here](https://github.com/pola-rs/polars/issues/11356).

Should be fixed now.

**Review by dkrako — APPROVED** [review]

**Pull request merged**
