### PR TITLE
feat!: add time column if missing during gaze initialization

### PR DESCRIPTION
**Pull request by dkrako**
## Description

During development of #382 I encountered potential bugs if there is no time column present.
For a robust implementation we need to guarantee that a time column exists.

Depends on #650 for pydocstyle ignores

## Implemented changes

During initialization, there's an if clause that checks for a passed time column. If there is none, one will be created with `pl.arange(0, len(self.frame))`

## How Has This Been Tested?

- [x] Updated tests to always have a time column, even in case of zero rows and no data

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by SiQube** [comment]
merge conflict

**Comment by dkrako** [comment]
I have improved the timesteps creation by taking account of the experiment sampling rate to create timesteps in millisecond unit.

**Review by prassepaul — APPROVED** [review]
all good.

**Comment by SiQube** [comment]
merge conflict

**Pull request merged**
