### PR TITLE
Remove velocities argument from IDT function

### PR DESCRIPTION
**Pull request by jakobchwastek**
## Description

Removed `velocities` argument from idt function since the velocities are not nesessary for the idt algorithm.

## Implemented changes

- [x] Remove `velocities` from function header and all code lines checking the value of this argument
- [ ] Remove the velocity calculation in the idt test functions

## Type of change 

- [x] Bug fix (non-breaking change which fixes an issue)
- 
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by dkrako** [comment]
This was implemented in #152 and is needed for #159 to work properly.

I know this solution was not 100% optimal but the easiest one to implement for now.

Please create an issue to discuss how we can do this in the future.

**Comment by dkrako** [comment]
Or maybe it's better that I reopen this again, we can have the discussion here too.

**Comment by jakobchwastek** [comment]
Ahh okay, thanks for the update. I missed this. I was just starting to do an example for idt and tought I initialy just copy/pasted the function header from ivt with the additional argument.

**Comment by dkrako** [comment]
No problem, it is actually a good idea to improve on this, and I already feared a bit that this will create usability issues.

But to fix the issue, we would now also need a more clever way of passing the arguments in this line:

https://github.com/aeye-lab/pymovements/blob/c833d5a74b6b3ee9e050db7619d6507cfecf2015/src/pymovements/datasets/dataset.py#L430

You could try to check the actual expected keyword arguments of the passed function via `inspect.getargspec()`

Moreover, I have defined an `EventDetectionCallable` protocol here:
https://github.com/aeye-lab/pymovements/blob/c833d5a74b6b3ee9e050db7619d6507cfecf2015/src/pymovements/events/events.py#L32-L56

If this protocol seems unpractical we can either get rid of it again or create two more protocols for velocity and position only detection methods.

**Review by dkrako — CHANGES_REQUESTED** [review]
As described above, this will need further changes in the datasets module.

**Comment by dkrako** [comment]
As this PR is now very behind the current main I created an separate issue for the broader case and close this PR

**Pull request closed without merging**
